# Generated by Django 5.2.8 on 2026-01-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
