# Generated by Django 5.2.7 on 2026-01-09 15:47

import django.core.validators
import django.db.models.deletion
import store.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('sub_title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='acceptance_payments/%Y/%m/%d/', validators=[store.validators.validate_image_size])),
                ('help_time', models.CharField(default=100, max_length=150)),
                ('shop_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '10. Acceptance Payments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('keyword', models.CharField(default='N/A', max_length=150)),
                ('description', models.CharField(default='N/A', max_length=150)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='brands/%Y/%m/%d/', validators=[store.validators.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '02. Brands',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '03. Product Colors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '04. Product Sizes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('keyword', models.CharField(default='N/A', max_length=150)),
                ('description', models.CharField(default='N/A', max_length=150)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='categories/%Y/%m/%d/', validators=[store.validators.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': '01. Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('color-size', 'Color Size'), ('none', 'None')], default='none', max_length=150)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('400000.00'), max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('available_stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('sold', models.PositiveIntegerField(default=0)),
                ('prev_des', models.TextField(default='N/A')),
                ('add_des', models.TextField(default='N/A')),
                ('short_des', models.TextField(default='N/A')),
                ('long_des', models.TextField(default='N/A')),
                ('keyword', models.TextField(default='N/A')),
                ('description', models.TextField(default='N/A')),
                ('tag', models.CharField(default='N/A', max_length=150)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_deadline', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name_plural': '05. Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='galleries/%Y/%m/%d/', validators=[store.validators.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name_plural': '07. Image Galleries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_type', models.CharField(choices=[('none', 'None'), ('slider', 'Slider'), ('add', 'Add'), ('feature', 'Feature'), ('promotion', 'Promotion')], default='none', max_length=10)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('paragraph', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='sliders/%Y/%m/%d/', validators=[store.validators.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': '08. Sliders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '09. Reviews',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_review')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('variant_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size')),
            ],
            options={
                'verbose_name_plural': '06. Product Variants',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_variant')],
            },
        ),
    ]
