# Generated by Django 5.2.7 on 2026-01-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_default',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
