# Generated by Django 5.2.8 on 2025-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
