# Generated by Django 5.2.7 on 2026-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('color-size', 'Color Size'), ('none', 'None')], default='none', max_length=150),
        ),
    ]
