# Generated by Django 5.2.8 on 2025-12-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_acceptancepayment_shop_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancepayment',
            name='help_time',
            field=models.CharField(default=100, max_length=150),
        ),
    ]
